name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-18.04
    env:
      DO_USERNAME: ${{ secrets.D_USERNAME }}
      DO_PASS: ${{ secrets.D_PASS }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag castellodev/echo-node:github
    - name: Log into Docker
      run: echo $DO_PASS > ~/docker_pass.txt && cat ~/docker_pass.txt | docker login --username $DO_USERNAME --password-stdin
    - run: docker push castellodev/echo-node:github
